### ISSUE TITLE
[BI Work] Create an investment fund relationships tab

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#13]
This is partly for docs, which I will write later, and partly for updating spreadsheet.

**Docs/description:**

In cases where an investment is part of a fund and the investing entity and investment fund are known:

- The `Organisation ID` and `Organisation Role Category` fields in the `Investments` tab SHOULD be used to describe the legal entity that has made the investment, i.e., the contracting party.
- The `Investment Fund Relationships` tab should be used to describe the relationship between the investing entity and its controlling entity:
  - `Investing Organisation ID` and `Investing Organisation Name` refer to the the organisation that holds the investment.
  - `Controlling Organisation ID` and `Controlling Organisation Name` refer to the organisation that controls, or has majority control over, the legal entity that holds the investment. Non-majority relationships MAY be be added, with accompanying notes.
  - Both the `Investing Organisation` and the `Controlling Organisation` MUST be in `Organisations` tab. 

Example:

> Project X is invested in by Big Issue Invest Ventures 2 LP, which has Big Issue Invest Ltd as its largest partner.
> 
> Both Big Issue Invest Ventures 2 LP and Big Issue Invest Ltd appear on the Organisations tab.
> 
> Big Issue Invest Ventures 2 LP appear on the investments tab because they hold the investment in Project X.
> 
> On the `Investment Fund Relationships` tab, Big Issue Invest Ventures 2 LP is the investing organisation. Big Issue Invest Ltd is the controlling organisation because it is the majority partner in Big Issue Invest Ventures 2 LP.

**Spreadsheet**

Investment tab: no change.

Outcome funds tab: no change.

Investment funds tab:

New tab

investment-fund-relationships:id
investment-fund-relationships:investing-organisation-id
investment-fund-relationships:investing-organisation-name
investment-fund-relationships:controlling-organisation-id
investment-fund-relationships:controlling-organisation-name
& meta fields as elsewhere

**Comment by ghost** [comment]
I'm curious about why this is at the project level and not at the organisation level. If 2 projects have the same legal entity that has made the investment (i.e., the contracting party) in both cases won't they have the same controlling entity, so put on Organisation directly and avoid duplicating data? Or are there issues with relevancy and/or public/private that need to be settled on a per project basis?

**Comment by ghost** [comment]
Discussed on call:

Instead we will put on the Organisation Spreadsheet a new tab:

> "Controlled By (Indigo ID, eg ORG-0467)" "Source"
> "ORG-0467"                       "source1"

Will need to add a source tab to the Organisation Spreadsheet

**Comment by ghost** [comment]
@ScatteredInk Can you very quickly review schema https://github.com/INDIGO-Initiative/database-app/blob/13-parent-orgs/indigo/jsonschema/organisation.json and spreadsheet https://github.com/INDIGO-Initiative/database-app/blob/13-parent-orgs/indigo/spreadsheetform_guides/organisation_v002.xlsx and tell me if that's what you were expecting?

**Comment by ScatteredInk** [comment]
Looks good - thanks @odscjames

**Comment by ghost** [comment]
Now live
