### ISSUE TITLE
Outcome Pricing tab

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#20]
New object Outcome Pricing. Rows on this tab should have 1-1 relationship with outcome metrics.

Outcome Metric ID
Outcome Pricing Currency
Outcome Price Per Unit
Contracted increases to outcome pricing (text)
Maximum Price if all targets achieved
Price Description (text)

**Comment by ScatteredInk** [comment]
Actually this will also need an ID field of its own, as potentially going to be referenced in transactions tab.

**Comment by ghost** [comment]
> Actually this will also need an ID field of its own, as potentially going to be referenced in transactions tab.

That would imply you can have more than one Outcome pricing per Outcome metric.

If it's one-to-one couldn't the transactions tab use the outcome metric ID?

**Comment by ghost** [comment]
>  Outcome Price Per Unit

I'm assuming in local and USD, as others

**Comment by ScatteredInk** [comment]
> If it's one-to-one couldn't the transactions tab use the outcome metric ID?

Ah yes, that would work. 

Yes on the currency Q.

**Comment by ghost** [comment]
>  Maximum Price if all targets achieved

Is that meant to be a number, and hence in local and USD as well? Can reuse same currency column, don't need a new one?

**Comment by ScatteredInk** [comment]
I think we can reuse as the measurement is at the same time and about the same thing.

**Comment by ghost** [comment]
So your saying yes to reuse currency. And Local/USD?

**Comment by ScatteredInk** [comment]
Yes to reusing currency. We don't need local and USD here because it is just about contracted values - anything converted would happen when there was a transaction only.

**Comment by ghost** [comment]
> We don't need local and USD here because it is just about contracted values - anything converted would happen when there was a transaction only.

So in effect it's a local price, and we just don't have USD for this one?

Also, is " Maximum Price if all targets achieved" really " Maximum Price **per unit** if all targets achieved"?

**Comment by ScatteredInk** [comment]
> Also, is " Maximum Price if all targets achieved" really " Maximum Price per unit if all targets achieved"?

This is a good question and something I want to check this because we need an aggregate figure somewhere for visualisations -and I'd rather have it calculated at source than derived.

**Comment by ghost** [comment]
Now live
