### ISSUE TITLE
Additional fields in project/overall_project_finance

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#21]
These have been added as a new tab with repeated info in the internal prototype. I think it is preferable to have these fields as additional fields in the original spreadsheet, where the extension is in use, as follows:

/overall_project_finance/total_funds_invested/latest_amount_currency - iso currency code
/overall_project_finance/total_funds_invested/latest_amount - number
/overall_project_finance/total_funds_invested/latest_date - date
/overall_project_finance/internal_rate_of_return/target_irr - number
/overall_project_finance/internal_rate_of_return/latest_irr - number
/overall_project_finance/internal_rate_of_return/latest_irr_date - date

These should be at the end of the overall_project_finance block.

**Comment by ghost** [comment]
>  /overall_project_finance/total_funds_invested/latest_amount - number

I'm assuming amount in local and USD as others

**Comment by ghost** [comment]
>  /overall_project_finance/total_funds_invested/latest_date - date

YYYY-MM like others?

**Comment by ScatteredInk** [comment]
Yes to both, thanks.

**Comment by ghost** [comment]
Now live
