### ISSUE TITLE
How do we tell if a proect is BI or not?

### ISSUE THREAD

**Issue by ghost** [INDIGO-Initiative/database-app#22]
On the front end, we want to list BI projects separately, which means on the back-end we want a way to separate out if a project is "BI" or not.

How can we do this?

* A special boolean field
* Just a rule - if a project has any data in for any of the new BI field, it's a BI projects?

**Comment by ScatteredInk** [comment]
A boolean I think.

**Comment by ghost** [comment]
Ok, what should the label / field name be?

**Comment by ScatteredInk** [comment]
Social Investment Prototype - true if it's part of the BII dataset.

**Comment by ghost** [comment]
Now live
