### ISSUE TITLE
Transactions tab

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#23]
A transaction may be associated with an investment, payment for an outcome metric or a grant. If no identifier is provided then transactions are associated with the project.

/investment_id
/outcome_metric_id
/grant_id (this tab doesn't exist yet - but it will)

/date (date - I think this could be a non-fuzzy date, potentially)
/sending_organisation/indigo_id
/sending_organisation/name
/receiving_organisation/indigo_id
/receiving_organisation_name
/transaction_type enum: ["debt", "grant", "equity", "debt and equity", "interest payment", "capital repayment", "capital repayment and interest", "outcome payment", "other"]
/local_currency
/amount_local
/amount_usd
/description

+meta/status block

**Comment by ghost** [comment]
> (date - I think this could be a non-fuzzy date, potentially)

What does this mean - YYYY-MM-DD instead of YYYY-MM?

**Comment by ghost** [comment]
I'm going to take the organisation name columns out for now. This might actually be a good idea and help with QC they mentioned but it's more complex and if we do it here there are several other places we could do it, so I would want to think about it carefully

**Comment by ScatteredInk** [comment]
Yes that makes sense. I added it in because the internal prototypes have used names in the ID fields, so the user need to identify/quality check via a name is quite strong.

**Comment by ghost** [comment]
Now live
