### ISSUE TITLE
Grants tab

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#25]
This reuses a subset of 360Giving fields, with an extended purpose enum from SEDL, and has the option to link out to published 360 data.

/Id
/360_giving_identifier
/title
/award_date
/currency
/local_amount_applied_for
/usd_amount_applied_for
/local_amount_awarded
/usd_amount_awarded
/local_amount_disbursed
/usd_amount_disbursed
/recipient_org/indigo_id
/funding_org/indigo_id
/description
/purpose enum: [acquisition,asset,bridgingLoan,capital,developmentCapital,growthFinance,multiple,programFunding,property,propertyRefurbishment,other,restructuringFinance,startupCosts,technicalAssistance,unrestricted,workingCapital]

meta + sources block

**Comment by ghost** [comment]
Should this be as well as the current 360 Tab? Replacing things technically gets complex (because what do you do about existing data, tho I would guess there isn't any yet) so I'm going to just say yes

**Comment by ghost** [comment]
>acquisition,asset,bridgingLoan,capital,developmentCapital,growthFinance,multiple,programFunding,property,propertyRefurbishment,other,restructuringFinance,startupCosts,technicalAssistance,unrestricted,workingCapital

I've changed these to have caps and spaces to match other enum lists here

**Comment by ScatteredInk** [comment]
> Should this be as well as the current 360 Tab?

Yes, I think so. Ideally you'd use one or the other tab, I think - I can document this.

**Comment by ghost** [comment]
Now live
