### ISSUE TITLE
Technical Assistance and Technical Assistance Details tabs

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#26]
**Tab name: Technical assistance**

ta_id
title
description
period_start - date
period_end - date
funding_organisation/indigo_id
recipient_organisation/indigo_id
currency

**Tab name: Technical assistance details**

ta_id
title
description
category - enum (see below),
approach - "enum": [
"SPO Board Seat (including Observers)",
"Coaching and mentoring",
"Trainings, Workshops and Boot Camps",
"Conferences and Other External Events",
"Access to Networks (External or Peers)"
"Specific Expertise (One-to-One or Groups)",
"Mentoring",
"Informal Relationship Management and Ad Hoc Support",
"Other Approach"
],
cost_type - enum:
[
"Purchased or spent",
"In-kind",
"Staff cost",
"Other"
],
cost_of_activities - number
number_of_days - number
+meta & source block

category enum:

[
"Overall TA - Planning - Project Management",
"Overall TA - Planning - Commissioning",
"Overall TA - Delivery - In-house Relationship",
"Overall TA - Delivery - In-house Specialist",
"Overall TA - Delivery - Pro-bono Partner",
"Overall TA - Delivery - External Consultant",
"Overall TA - Delivery - SPO Staff Member",
"Theory of Change and Impact Strategy - Support to develop the Theory of Change and Impact Strategy",
"Theory of Change and Impact Strategy - Support to develop an evaluation framework and performance measures",
"Developing an Impact Measurement System",
"Fundraising - Assistance securing funding from other sources",
"Fundraising - Use VPO's reputation to help grantees secure funding from other sources",
"Fundraising -  Practical support with fundraising",
"Fundraising - Fundraising advice or strategy",
"Fundraising - Assistance securing follow-on funding",
"Revenue Strategy - Business Planning",
"Revenue Strategy - Business Model Development or Business Model Canvas)",
"Financial Management - Sound Financial Management Capabilities or Financial Management Tools",
"Financial Management - Develop Financial Systems",
"Financial Management - Financial Management Advice",
"Financial Management - Financial Planning or Accounting",
"Financial Management - Support To Establish New Financial Systems",
"Human Capital Support -  Strengthening CEO And Management Team (Coaching And Mentoring",
"Human Capital Support - Recruitment And Talent Provision",
"Governance Support - Support to Develop Board of Directors",
"Governance Support - Advice or Assistance to Strengthen the Board or Governance System",
"Governance Support -  Board Development or Governance Assistance",
"Governance Support - Assistance in Recruitment of New Board Members",
"Strategic Support - Strategy Consulting",
"Strategic Support - General Management Advice",
"Strategic Support - Strategic Planning Advice",
"Strategic Support - Support to Develop the Business Strategy",
"Strategic Support - Support to Develop New Products or Services",
"Strategic Support - Support to Develop New Business Systems or Procedures",
"Strategic Support - Advice on management of change"
"Operational Support - Marketing",
"Operational Support - Operational Management",
"Operational Support - Technical Assistance in Specialist Areas",
"Operational Support - ICT Advice",
"Operational Support - Support on Procurement",
"Operational Support - Estate Management or Access to Physical Space",
"Operational Support - Legal Advice",
"Funding - Financing Capacity Building Grants and Awards - Specific money allocated for non-financial support",
"Funding - Financing Capacity Building Grants and Awards - VPOs and VPO’s funders allocate specific resources to non-financial support",
"Funding - Financing Unrestricted Grants or Funding - Give unrestricted funding for capacity building",
"Funding - Financing Unrestricted Grants or Funding - VPOs and VPO’s funders allocate specific resources to non-financial support/external donations",
"Funding - Financing Grants and Contacts with External Capacity-building Providers - Develop Network of Capacity-building Providers",
"Funding - Financing Grants and Contacts with External Capacity-building Providers - External Parties Giving Support For Free",
"Funding - Financing Capacity Building Through Collaboration Among Funders And Beyond - Investors Team Up To Address Capacity-building Challenges",
"Funding - Financing Capacity Building Through Collaboration Among Funders And Beyond - VPOs and VPO’s Funders Allocate Specific Resources to Non-financial Support",
"Funding - Financing Management Fees",
"Funding -  Financing the SPO to Pay for Non-financial Support or Matching",
"Funding - Financing Corporate Partners",
"Funding - Financing a VPO Subsidy"
]

**Comment by ghost** [comment]
>period_start - date
>period_end - date

YYYY-MM again?

>  cost_of_activities - number

local and USD? I think you said just local before but do confirm

**Comment by ScatteredInk** [comment]
> YYYY-MM again?

Yes.

> cost_of_activities - number

Just local.

**Comment by ghost** [comment]
@ScatteredInk 

Please review schema
https://github.com/INDIGO-Initiative/database-app/commit/746b02be1654ccca5fd8e0855fd1feedb64442f6#diff-b4a53e6e10c0fb26e425ce43188a71e0

and Spreadsheet
https://github.com/INDIGO-Initiative/database-app/blob/746b02be1654ccca5fd8e0855fd1feedb64442f6/indigo/spreadsheetform_guides/project_v005.xlsx


Had a problem.

Turns out Libreoffice, while saving to XLSX will only let you put a certain amount of characters in a data-validity list field. If goes in fine in app, save and open again, anything beyond a limit is gone.

For now, 'cos we need this up, I've stuck the values in a new sheet. No validity. People can copy and paste.

**Comment by ScatteredInk** [comment]
Thanks @odscjames 

Is the validation being done with openpyxl or just manually? I think it works OK in LibreOffice if you use validation via a cell range (data - validity - cell range) - or at least I've saved and reopened successfully doing it this way. If that's an acceptable workaround, we could just hide or rename this extra tab to avoid mishaps. I think for this one we want a dropdown if at all possible as that's the trade-off for moving to two tabs.

**Comment by ghost** [comment]
There is several places the validity could/should be done but in this case it needs to be set up in the Excel file. I'm trying cell range and a hidden sheet ....

**Comment by ghost** [comment]
@ScatteredInk Got cell range and hidden sheet, 

Schema: https://github.com/INDIGO-Initiative/database-app/commit/5399214629fd5905a190f6797e28ac0655759085#diff-b4a53e6e10c0fb26e425ce43188a71e0
Sheet: https://github.com/INDIGO-Initiative/database-app/blob/5399214629fd5905a190f6797e28ac0655759085/indigo/spreadsheetform_guides/project_v005.xlsx

**Comment by ScatteredInk** [comment]
This looks good - thanks.

**Comment by ghost** [comment]
Live
