### ISSUE TITLE
Policy Sector and Stage of Development normalisation

### ISSUE THREAD

**Issue by Lathrisk** [INDIGO-Initiative/database-app#27]
The pie charts are generated directly from the data. In this case, there are slight differences in the values used. For example, the policy sector for 29 of the projects is "Homelessness", but there is one where space has been added to the end of the value, "Homelessness ". This has created duplicate values in the chart. And there are some which have a different case, or ampersands vs words (i.e. ‘Education and early years’ vs ‘Education and Early Years’, and ‘Health and wellbeing’ vs ‘Health & wellbeing’).

If we can normalise these towards the codelist that would be ideal. The alternative suggested by Golab is to remove the pie charts completely for launch.

This should be done for Policy Sector (purpose_and_classifications/policy_sector/value) and Stage of Development (stage_development/value), ideally.

**Comment by ghost** [comment]
Live
