### ISSUE TITLE
Add ranges to investment commitment

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#5]
For fields in the investment block, in addition to exact numbers, ranges are required.

I suggest:

project/
Total investment commitment in project currency, Exact
Total investment commitment in USD, Exact
Total investment commitment in project currency, Minimum
Total investment commitment in USD, Minimum
Total investment commitment in project currency, Maximum
Total investment commitment in USD,  Maximum

investments/

Investment commitment in investment currency, Exact
Investment commitment in USD, Exact
Investment commitment in investment currency, Minimum
etc

**Comment by ghost** [comment]
Done

**Comment by ghost** [comment]
Oh wait @ScatteredInk should "Total outcome payments made" have this too?

**Comment by ghost** [comment]
And "Total outcome payments made"?

The "etc" there is confusing me basically

**Comment by ScatteredInk** [comment]
No - ranges are just intended for the investment fields so the way you have done it is right. Sorry for being too lazy to type the fields out explicitly.
