### ISSUE TITLE
New field for General Overview tab - project jurisdiction

### ISSUE THREAD

**Issue by ScatteredInk** [INDIGO-Initiative/database-app#63]
Not signed off yet but current suggestion is:

Add:

project_jurisdiction

to: 

Row 7 of the overview tab (with the name block)

This should be an ISO 3166-1 alpha-2 country code.

**Comment by ghost** [comment]
So singular not list? Ok.

Do we mean:

A) In a new block between name and stage of development? 
B) In the existing name block?

I think I would lean towards A because this field should have the status, sources and notes fields that others have and names don't have that.

**Comment by ScatteredInk** [comment]
Yes, singular - and let's go for option A please.

**Comment by ghost** [comment]
This is done and live (don't know why didn't close at time)
